// frontend/src/lib/components/announcements/Announcement.svelte
<script lang="ts">
  import { mdiAlertOutline, mdiInformationOutline } from '@mdi/js';

  import SvgIcon from '$lib/components/SVGIcon.svelte';
  import { type Announcement, AnnouncementImportance } from '$lib/generated';
  import { viewedAnnouncements } from '$lib/store/settingsStore';
  import { markdown as renderMarkdown } from '$lib/utils/markdown';

  export let announcement: Pick<Announcement, 'id' | 'importance' | 'message'>;

  $: importanceLower = announcement.importance.toLowerCase();
  $: isNew = !$viewedAnnouncements.includes(announcement.id);
  $: icon = (() => {
    switch (announcement.importance) {
      case AnnouncementImportance.Alert:
      case AnnouncementImportance.Warning:
        return mdiAlertOutline;
      case AnnouncementImportance.Fix:
      case AnnouncementImportance.Info:
      default:
        return mdiInformationOutline;
    }
  })();

  $: rendered = renderMarkdown(announcement.message);
</script>

<div class="announcement-{importanceLower} announcement-bg p-1.5 h-full" class:announcement-new={isNew}>
  <div class="flex items-center announcement-bg-text p-1 h-full">
    <SvgIcon class="w-8 h-8 mr-3 shrink-0" icon={icon} />
    <div class="grow wrap text-lg">
      <slot>
        <div class="announcement-markdown-content">
          <!-- eslint-disable-next-line svelte/no-at-html-tags -->
          {@html rendered}
        </div>
      </slot>
    </div>
  </div>
</div>


<style scoped>
  .announcement-alert {
    --deg: 15deg;
  }
  .announcement-warning {
    --deg: 30deg;
  }
  .announcement-fix {
    --deg: 80deg;
  }
  .announcement-info {
    --deg: 186deg;
  }
  @keyframes slide {
    from {
      background-position-x: -113px;
    }
    to {
      background-position-x: 0px;
    }
  }
  .announcement-bg-text {
    --colour1: hsl(var(--deg) 100% 36%);
    background-color: var(--colour1);
    border-radius: 5px;
  }
  .announcement-bg {
    --colour1: hsl(var(--deg) 100% 36%);
    --colour2: hsl(var(--deg) 77% 24%);
    background-size: 200% 100% !important;
    background-color: var(--colour1);
    will-change: background-position;
    background-image: repeating-linear-gradient(
        45deg,
        transparent,
        transparent 20px,
        var(--colour2) 20px,
        var(--colour2) 40px
    );
  }
  .announcement-new.announcement-bg {
    animation: slide 6s linear infinite;
  }
</style>

// src/renderer/components/announcements-bar/Announcement.vue
<template>
  <v-row
    align="center"
    no-gutters
    class="py-1 announcement-bg"
    :class="{ [`announcement-${importanceLower}`]: true,
              'announcement-new': isNew } "
  >
    <v-row
      align="center"
      no-gutters
      class="mx-1 announcement-bg-text"
      :class="`announcement-${importanceLower}`"
    >
      <v-col
        cols="auto"
        class="pl-4 pr-4"
      >
        <v-icon
          style="font-size: 32px !important"
          :color="announcementFgColor"
        >
          {{ announcementIcon }}
        </v-icon>
      </v-col>
      <v-col
        cols="10"
        :style="`color: ${announcementFgColor} !important;`"
      >
        <!-- eslint-disable-next-line vue/no-v-html -->
        <span v-html="announcementMessageHTML" />
      </v-col>
    </v-row>
  </v-row>
</template>

<script>
import { markdownAsElement } from '@/utils';
import { getSetting, saveSetting } from '~/settings';

export default {
  props: {
    announcement: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
      isNew: false,
    };
  },
  computed: {
    importanceLower() {
      return this.announcement.importance.toLowerCase();
    },
    announcementIcon() {
      switch (this.importanceLower) {
        case 'alert':
          return 'mdi-alert-outline';
        case 'warning':
          return 'mdi-alert-outline';
        case 'fix':
          return 'mdi-information-outline';
        case 'info':
        default:
          return 'mdi-information-outline';
      }
    },
    announcementBgColor() {
      switch (this.importanceLower) {
        case 'alert':
          return '#bb2828';
        case 'warning':
          return '#ffcc00';
        case 'fix':
          return '#249a20';
        case 'info':
        default:
          return '#5daec5';
      }
    },
    announcementFgColor() {
      switch (this.importanceLower) {
        default:
          return 'white';
      }
    },
    announcementMessageHTML() {
      const el = markdownAsElement(this.announcement.message);
      // get content from inside paragraph
      return el.children[1].children[0].innerHTML;
    },
  },
  mounted() {
    this.isNew = !getSetting('viewedAnnouncements', []).includes(this.announcement.id);
    if (this.isNew) {
      setTimeout(() => {
        const viewedAnnouncements = getSetting('viewedAnnouncements', []);
        viewedAnnouncements.push(this.announcement.id);
        saveSetting('viewedAnnouncements', viewedAnnouncements);
        this.isNew = false;
      }, 60 * 1000);
    }
  },
};
</script>

<style scoped>
.announcement-alert {
  --deg: 15deg;
}

.announcement-warning {
  --deg: 30deg;
}

.announcement-fix {
  --deg: 80deg;
}

.announcement-info {
  --deg: 186deg;
}

@keyframes slide {
  from {
    background-position-x: -113px;
  }
  to {
    background-position-x: 0px;
  }
}

.announcement-bg-text {
  --colour1: hsl(var(--deg) 100% 36%);
  background-color: var(--colour1);
  border-radius: 5px;
}

.announcement-bg {
  --colour1: hsl(var(--deg) 100% 36%);
  --colour2: hsl(var(--deg) 77% 24%);
  background-size: 200% 100% !important;
  background-color: var(--colour1);
  will-change: background-position;
  background-image: repeating-linear-gradient(
      45deg,
      transparent,
      transparent 20px,
      var(--colour2) 20px,
      var(--colour2) 40px
  );
}

.announcement-new.announcement-bg {
  animation: slide 6s linear infinite;
}
</style>
