// src/renderer/components/TitleBar.vue
<template>
  <div class="titlebar">
    <div
      class="d-inline-flex align-items-center"
      @click="settingsClicked"
    >
      <v-icon
        :color="getColorForState"
        class="ma-1 icon"
      >
        mdi-cog
      </v-icon>
    </div>
    <div class="bar">
      <div class="dragregion">
        <span class="app-title">{{ title }}</span>
      </div>
      <div
        class="button close"
        @click="onClose"
      >
        <span>&#10005;</span>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    state: {
      type: String,
      validator: (prop) => [
        'off',
        'on',
        'notify',
      ].includes(prop),
      default: 'off',
    },
    title: {
      type: String,
      default: '',
    },
  },
  computed: {
    getColorForState() {
      if (this.state === 'notify') {
        return '#ffc107';
      }
      if (this.state === 'on') {
        return 'primary';
      }
      return '#9e9e9e';
    },
  },
  methods: {
    onClose() {
      this.$electron.remote.getCurrentWindow().close();
    },
    settingsClicked() {
      this.$emit('settingsClicked');
    },
  },
};
</script>

<style scoped>
.app-title {
  font-size: 16px !important;
}
.titlebar {
  display: flex;
  height: var(--titlebar-height);
}
.titlebar, .titlebar > *, .titlebar > * > * {
  color: var(--v-text2-base) !important;
  background-color: var(--v-background-base);
}
.icon {
  font-size: 16px !important;
  padding: 3px 0px 0px 3px;
}
.bar {
  flex-grow: 1;
  display: flex;
}
.dragregion {
  flex-grow: 1;
  text-align: center;
  vertical-align: middle;
  margin: 3px 3px 0px 0px;
  -webkit-app-region: drag;
  display: flex;
  align-items: center;
}
.dragregion>span {
  flex-grow: 1;
  margin-top: -3px;
}
.button {
  width: 44px;
  text-align: center;
  font-size: 12pt;
  display: flex;
  align-items: center;
  cursor: pointer;
  color: var(--v-text-base);
}
.button>span {
  flex-grow: 1;
  margin-top: -3px;
  user-select: none;
}
.button:hover {
  background-color: var(--titlebar-button-hover-color);
}
.close:hover {
  background-color: red;
  color: white;
}
.button>span.dash {
  vertical-align: sub;
  margin-top: 0px;
}
#settingsIcon {
  height: 18px;
  margin: 4.5px;
}
</style>

// frontend/src/lib/components/TitleBar.svelte
<script lang="ts">
  import MDIIcon from './MDIIcon.svelte';
  import { mdiWindowMinimize, mdiWindowRestore, mdiWindowMaximize, mdiWindowClose } from '@mdi/js';
  import { Quit, WindowMinimise, WindowToggleMaximise } from '../../../wailsjs/runtime';

  function minimize() {
    WindowMinimise();
  }

  function toggleMaximize() {
    WindowToggleMaximise();
  }

  function close() {
    Quit();
  }

  let isMaximized = false;
</script>

<div class="titlebar">
  <div class="inline-flex items-center">
    <img src="/images/smm_icon_small.png" class="app-icon" alt="SMM Icon" />
  </div>
  <div class="bar">
    <div class="dragregion" data-wails-drag>
      <span class="app-title">Satisfactory Mod Manager</span>
    </div>
    <div class="button minimize grid place-items-center" on:click={minimize}>
      <MDIIcon icon={mdiWindowMinimize} />
    </div>
    <div class="button maximize grid place-items-center" on:click={toggleMaximize}>
      {#if isMaximized}
        <MDIIcon icon={mdiWindowRestore} />
      {:else}
        <MDIIcon icon={mdiWindowMaximize} />
      {/if}
    </div>
    <div class="button close grid place-items-center" on:click={close}>
      <MDIIcon icon={mdiWindowClose} />
    </div>
  </div>
</div>

<style scoped>
  .app-title {
    font-size: 15px !important;
    color: var(--v-text-lighten2);
  }
  .app-icon {
    margin: 4px 0px 4px 10px;
    height: 25px;
  }
  .titlebar {
    display: flex;
    user-select: none;
    z-index: 9999;
  }
  .titlebar,
  .titlebar > * {
    color: var(--v-text2-base) !important;
    background-color: var(--v-background-base);
  }
  .bar {
    flex-grow: 1;
    display: flex;
  }
  .dragregion {
    flex-grow: 1;
    text-align: left;
    vertical-align: middle;
    margin: 4px 3px 0px 10px;
    -webkit-app-region: drag;
  }
  .dragregion > span {
    flex-grow: 1;
    margin-top: -4px;
  }
  .button {
    width: 44px;
    text-align: center;
    font-size: 12pt;
    cursor: pointer;
    color: var(--v-text-base);
  }
  .button:hover {
    background-color: gray;
    color: white !important;
  }
  .close:hover {
    background-color: red;
    color: white !important;
  }
</style>
