// frontend/src/lib/components/mods-list/ModsList.svelte
<script lang="ts">
  import { getClient } from '@urql/svelte';
  import { GetModsDocument, GetModCountDocument } from '$lib/generated';
  import ModsListItem from '$lib/components/mods-list/ModsListItem.svelte';
  import _ from 'lodash';
  import Fuse from 'fuse.js';
  import ModListFilters from './ModsListFilters.svelte';
  import { orderByOptions, type OrderBy, type PartialMod } from '$lib/components/mods-list/modFilters';

  let mods: PartialMod[] = [];

  const MODS_PER_PAGE = 50;

  const urqlClient = getClient();

  async function fetchAllMods() {
    const result = await urqlClient.query(GetModCountDocument).toPromise();
    const count = result.data?.getMods.count;
    if (count) {
      const pages = Math.ceil(count / MODS_PER_PAGE);

      mods = (await Promise.all(Array.from({length: pages}).map(async (_, i) => {
        const offset = i * MODS_PER_PAGE;
        const result = await urqlClient.query(GetModsDocument, { offset, limit: MODS_PER_PAGE }).toPromise();
        return result.data?.getMods.mods ?? [];
      }))).flat();
    }
  }

  fetchAllMods();

  let searchString = '';
  let order: OrderBy = orderByOptions[1];

  $: filteredMods = () => {
    const sortedMods = _.sortBy(mods, order.func) as PartialMod[];
    if(!searchString) {
      return sortedMods;
    }
    
    const modifiedSearchString = searchString.replace(/(?:author:"(.+?)"|author:([^\s"]+))/g, '="$1$2"');
    
    const fuse = new Fuse(sortedMods, {
      keys: [
        {
          name: 'name',
          weight: 2,
        },
        {
          name: 'short_description',
          weight: 1,
        },
        {
          name: 'full_description',
          weight: 0.75,
        },
        {
          name: 'authors.user.username',
          weight: 0.4,
        },
      ],
      useExtendedSearch: true,
      threshold: 0.2,
      ignoreLocation: true,
    });
    return fuse.search(modifiedSearchString).map((result) => result.item);
  };

  export let selectedMod: string | null = null;
  export let compact: boolean;
</script>

<div class="h-full flex flex-col">
  <div class="flex-none">
    <ModListFilters bind:search={searchString} bind:order={order} bind:compact={compact} />
  </div>
  <div class="py-4 grow h-0 mods-list" style="position: relative;">
    <!-- <div v-if="topShadow" class="list-shadow-top" />
    <div v-if="bottomShadow" class="list-shadow-bottom" /> -->
    <div class="ml-5 mr-3 overflow-y-scroll h-full">
      {#each filteredMods() as mod}
        <ModsListItem {mod} on:click={() => selectedMod = mod.mod_reference} bind:compact={compact} selected={selectedMod == mod.mod_reference}/>
      {/each}
    </div>
  </div>
</div>

<style>
  /* .list-shadow-top,
  .list-shadow-bottom {
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    z-index: 2;
    background: transparent !important;
    pointer-events: none;
  }
  .list-shadow-top {
    box-shadow: inset 0px 45px 20px -20px rgba(0, 0, 0, 0.3);
  }
  .list-shadow-bottom {
    box-shadow: inset 0px -45px 20px -20px rgba(0, 0, 0, 0.3);
  } */
  .mods-list {
    background-color: #2B2B2B;
  }
  ::-webkit-scrollbar {
    width: 25px;
  }
  ::-webkit-scrollbar-track {
    background: black;
    border: solid 10px transparent;
    background-clip: content-box;
    border-radius: 0;
  }
  ::-webkit-scrollbar-thumb {
    background: #fff;
    border: solid 10px transparent;
    border-top-width: 0px;
    border-bottom-width: 0px;
    background-clip: content-box;
    border-radius: 0;
  }
  ::-webkit-scrollbar-thumb:hover {
    border: solid 10px transparent;
    border-top-width: 0px;
    border-bottom-width: 0px;
    background-clip: content-box;
  }
</style>

// src/renderer/components/mods-list/ModsList.vue
<template>
  <div
    class="py-4"
    style="position: relative;"
  >
    <div
      v-if="topShadow"
      class="list-shadow-top"
    />
    <div
      v-if="bottomShadow"
      class="list-shadow-bottom"
    />
    <div
      ref="modsList"
      style="overflow-y: scroll; height: 100%;"
      class="ml-4"
      @scroll="modsListScrolled"
    >
      <v-list
        class="pt-3 mt-n4 custom"
      >
        <template
          v-for="(mod, index) in mods"
        >
          <ModsListItem
            :key="index"
            :mod="mod"
          />
        </template>
      </v-list>
    </div>
  </div>
</template>

<script>
import { mapState, mapGetters } from 'vuex';
import { lastElement, setIntervalImmediately, isCompatibleFast } from '@/utils';
import Fuse from 'fuse.js';
import debounce from 'debounce';
import gql from 'graphql-tag';
import ModsListItem from './ModsListItem';
import { getSetting, saveSetting } from '~/settings';

const MODS_PER_QUERY = 50;

export default {
  components: {
    ModsListItem,
  },
  props: {
    filters: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
      topShadow: false,
      bottomShadow: true,
      mods: [],
      availableMods: [],
      hiddenInstalledMods: [],
      compatibleMods: [],
      availableFilters: [
        {
          name: 'All mods',
          filter(mods) {
            return mods;
          },
          mods: 0,
        },
        {
          name: 'Compatible',
          filter(mods, vm) {
            return vm.compatibleMods;
          },
          mods: 0,
        },
        {
          name: 'Favourite',
          filter(mods, vm) {
            return mods.filter((mod) => vm.$store.state.favoriteModIds.includes(mod.mod_reference));
          },
          mods: 0,
        },
        {
          name: 'Installed',
          filter(mods, vm) {
            const installedMods = Object.keys(vm.$store.state.installedMods);
            return mods.filter((mod) => installedMods.includes(mod.mod_reference));
          },
          mods: 0,
        },
        {
          name: 'Not installed',
          filter(mods, vm) {
            const installedMods = Object.keys(vm.$store.state.installedMods);
            return mods.filter((mod) => !installedMods.includes(mod.mod_reference));
          },
          mods: 0,
        },
      ],
      availableSorting: [
        {
          name: 'Last updated',
          sort(mods) {
            return mods.sort((a, b) => b.last_version_date - a.last_version_date);
          },
        },
        {
          name: 'Name',
          sort(mods) {
            return mods.sort((a, b) => a.name.localeCompare(b.name));
          },
        },
        {
          name: 'Popularity',
          sort(mods) {
            return mods.sort((a, b) => b.popularity - a.popularity);
          },
        },
        {
          name: 'Hotness',
          sort(mods) {
            return mods.sort((a, b) => b.hotness - a.hotness);
          },
        },
        {
          name: 'Views',
          sort(mods) {
            return mods.sort((a, b) => b.views - a.views);
          },
        },
        {
          name: 'Downloads',
          sort(mods) {
            return mods.sort((a, b) => b.downloads - a.downloads);
          },
        },
      ],
    };
  },
  computed: {
    ...mapState([
      'favoriteModIds',
      'expandedModId',
      'inProgress',
      'installedMods',
    ]),
    ...mapGetters([
      'canInstallMods',
    ]),
    search() {
      return this.filters.search;
    },
    hiddenInstalledModReferences() {
      return Object.keys(this.$store.state.installedMods)
        .filter((modID) => !this.availableMods.some((mod) => mod.mod_reference === modID)) // not in the available mods list
        .filter((modID) => this.$store.state.manifestMods[modID] !== undefined); // not dependency
    },
    allMods() {
      return [...this.availableMods, ...this.hiddenInstalledMods].filter((mod, idx, arr) => arr.findIndex((other) => other.mod_reference === mod.mod_reference) === idx);
    },
    filteredMods() {
      if (!this.filters.modFilters?.filter || !this.filters.sortBy?.sort) { return this.allMods; }
      // eslint-disable-next-line vue/no-side-effects-in-computed-properties
      return this.filters.sortBy.sort(this.filters.modFilters.filter(this.allMods, this));
    },
  },
  apollo: {
    hiddenInstalledMods: {
      query: gql`
        query getHiddenInstalledMods($references: [String!]) {
          getMods(filter: { references: $references, hidden: true }) {
            mods {
              id,
              name,
              mod_reference,
              downloads,
              views,
              popularity,
              hotness,
              logo,
              hidden,
              last_version_date,
              versions(filter: { limit: 100 }) {
                id,
                sml_version,
              }
            }
          }
        }
      `,
      variables() {
        return {
          references: this.hiddenInstalledModReferences,
        };
      },
      update: (data) => data.getMods.mods,
    },
  },
  watch: {
    mods() {
      this.$nextTick(() => this.modsListScrolled());
    },
    search() {
      this.updateSearch();
    },
    filteredMods() {
      this.updateSearch();
    },
    filters(newValue, oldValue) {
      if (newValue.modFilters !== oldValue.modFilters || newValue.sortBy !== oldValue.sortBy) {
        saveSetting('filters', { modFilters: this.filters.modFilters.name, sortBy: this.filters.sortBy.name });
      }
    },
    async allMods(allMods) {
      if (!this.$store.state.selectedInstall) {
        this.compatibleMods = [];
        return;
      }
      const { version } = this.$store.state.selectedInstall;
      this.compatibleMods = (await Promise.all(allMods.map(async (mod) => ((await isCompatibleFast(mod, version)) ? mod : null)))).filter((mod) => !!mod);
      this.availableFilters.forEach(async (filter) => { filter.mods = filter.filter(allMods, this).length; });
    },
    installedMods() {
      this.availableFilters.forEach(async (filter) => { filter.mods = filter.filter(this.allMods, this).length; });
    },
    favoriteModIds() {
      this.availableFilters.forEach(async (filter) => { filter.mods = filter.filter(this.allMods, this).length; });
    },
  },
  mounted() {
    this.$emit('set-available-filters', this.availableFilters);
    this.$emit('set-available-sorting', this.availableSorting);

    this.$nextTick(() => {
      setIntervalImmediately(async () => {
        const availableModsCount = (await this.$apollo.query({
          query: gql`
            query getMods {
              availableMods: getMods {
                count
              }
            }
          `,
        })).data.availableMods.count;
        if (availableModsCount !== this.availableMods.length) {
          this.availableMods = (await Promise.all(Array.from({ length: Math.ceil(availableModsCount / MODS_PER_QUERY) }).map(async (_, page) => (await this.$apollo.query({
            query: gql`
              query getMods($limit: Int!, $offset: Int!) {
                availableMods: getMods(filter: { limit: $limit, offset: $offset }) {
                  mods {
                    id,
                    name,
                    mod_reference,
                    downloads,
                    views,
                    popularity,
                    hotness,
                    logo,
                    hidden,
                    last_version_date,
                    versions(filter: { limit: 100 }) {
                      id,
                      sml_version,
                    }
                  }
                }
              }
            `,
            variables: {
              limit: MODS_PER_QUERY,
              offset: page * MODS_PER_QUERY,
            },
          })).data.availableMods.mods))).flat(1);
        }
      }, 5 * 60 * 1000);
    });

    const savedFilters = getSetting('filters', { modFilters: this.availableFilters[1].name, sortBy: this.availableSorting[0].name }); // default Compatible, Last Updated
    this.$emit('update:filters', {
      modFilters: this.availableFilters.find((modFilter) => modFilter.name === savedFilters.modFilters) || this.availableFilters[1], // default Compatible
      sortBy: this.availableSorting.find((item) => item === savedFilters.sortBy) || this.availableSorting[0], // default Last Updated
      search: '',
    });
    this.updateSearch('');
  },
  methods: {
    modsListScrolled() {
      this.topShadow = this.$refs.modsList.scrollTop > 0;
      this.bottomShadow = this.$refs.modsList.scrollTop + this.$refs.modsList.offsetHeight < this.$refs.modsList.scrollHeight;
    },
    updateSearch: debounce(function updateSearch() {
      let searchString = this.search;
      if (searchString === '') {
        this.mods = this.filteredMods;
        return;
      }
      searchString = searchString.replace(/(?:author:"(.+?)"|author:([^\s"]+))/g, '="$1$2"');

      const fuse = new Fuse(this.filteredMods, {
        keys: [
          {
            name: 'name',
            weight: 2,
          },
          {
            name: 'short_description',
            weight: 1,
          },
          {
            name: 'full_description',
            weight: 0.75,
          },
          {
            name: 'authors.user.username',
            weight: 0.4,
          },
        ],
        useExtendedSearch: true,
        threshold: 0.15,
        minMatchCharLength: searchString.length * 0.8,
      });
      this.mods = fuse.search(searchString).map((result) => result.item);
    }),
    async isCompatible(mod) {
      return isCompatibleFast(mod, this.$store.state.selectedInstall.version);
    },
    lastElement,
  },
};
</script>

<style scoped>
div {
  background: var(--v-backgroundModsList-base) !important;
}

.list-shadow-top, .list-shadow-bottom {
  position: absolute;
  width: 100%;
  height: 100%;
  top: 0;
  z-index: 1;
  background: transparent !important;
  pointer-events: none;
}

.list-shadow-top {
  box-shadow: inset 0px 45px 20px -20px rgba(0,0,0,0.3);
}
.list-shadow-bottom {
  box-shadow: inset 0px -45px 20px -20px rgba(0,0,0,0.3);
}

::-webkit-scrollbar-track {
  background: var(--v-background-base);
  border: solid 9px transparent;
  background-clip: content-box;
  border-radius: 100px;
}
::-webkit-scrollbar-thumb {
  background: var(--v-background-base);
  border: solid 3.5px transparent;
  background-clip: content-box;
  border-radius: 20px;
}
::-webkit-scrollbar-thumb:hover {
  border: solid 3.5px transparent;
  background-clip: content-box;
}
</style>
